baseURL = "/"
languageCode = "en-us"
title = "Project 2 â€“ Secure REST API with Docker Deployment"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = false
  ShowPostNavLinks = true

[[menu.main]]
  identifier = "overview"
  name = "Overview"
  url = "/overview/"
  weight = 1

[[menu.main]]
  identifier = "api"
  name = "API Endpoints"
  url = "/api/"
  weight = 2

[[menu.main]]
  identifier = "docker"
  name = "Docker Setup"
  url = "/docker/"
  weight = 3

[[menu.main]]
  identifier = "deploy"
  name = "Deployment"
  url = "/deploy/"
  weight = 4

[[menu.main]]
  identifier = "testing"
  name = "Testing"
  url = "/testing/"
  weight = 5

[[menu.main]]
  identifier = "screenshots"
  name = "Screenshots"
  url = "/screenshots/"
  weight = 6
